# Generated by Django 5.1.1 on 2024-10-06 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LittleLemonAPI', '0002_remove_cart_price_remove_orderitem_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='unitprice',
        ),
    ]
